FROM ubuntu:latest

COPY ./target/maven-jlink/default/ /usr/app/

WORKDIR /usr/app/podaci

EXPOSE 8000
EXPOSE 8001
EXPOSE 8002
EXPOSE 8011

CMD ["sh", "-c", "sleep 1 && /usr/app/bin/java -m vvugrinec21_vjezba_08_dz_3_partner/edu.unizg.foi.nwtis.vvugrinec21.vjezba_08_dz_3.PosluziteljPartner NWTiS_04_partner_1.txt PARTNER"]
